### ISSUE TITLE
Unusual behavior when using raw input in address search

### ISSUE THREAD

**Issue by maptastik** [mapzap/mapzap.github.io#2]
When using the Address search, it appears that the user must select one of the address from the dropdown. I've tested this in Chrome and Firefox. Each browser reacts differently.

## Chrome
If the user instead opts for a fully manually inputed address string, the app enters into what appears to be an infinite reloading loop in which the string `build.html` is appended to and accumulates at the end of the url `mapzap.github.io/?`. 

![mapzap-address-error](https://user-images.githubusercontent.com/3319507/30241008-3d50b194-9549-11e7-923e-21341df4d490.gif)

I was able to return to the app state by hitting *Back* a couple times.

## Firefox

Testing the same situation in Firefox, the app redirects to `mapzap.github.io/build.html`.

![mapzap-address-error-ff](https://user-images.githubusercontent.com/3319507/30241066-8a9d66f8-954a-11e7-924d-a50c8372120c.gif)

In the Firefox developer tools console, an error pops up for an instant just before the redirect to the `build.html` page. I was able to catch a screenshot of that:

![mapzap-search-error-ff](https://user-images.githubusercontent.com/3319507/30241142-86a14e6a-954b-11e7-9a02-355fde286b74.png)

## Moving forward

I think users will expect that if they enter something in the address search bar, they will, for better or worse, get a map view based off on their raw input as this is what can be done using the Google Maps app. Just some ideas off the top of my head about how to approach dealing with this issue:

- Upon selecting the raw input, center the map on the first address in the dropdown list.
- Restrict the app from accepting raw input addresses and instruct users to select an address from the dropdown list. 
- Something else entirely!

I may have some time this weekend to look into this more, but am curious if there are other ideas on how to approach this issue.

**Comment by bmcbride** [comment]
Good catch! Looking into it now. I'll probably push a temporary fix for that nasty redirect until I can come up with a better solution.
