### ISSUE TITLE
Add Features?

### ISSUE THREAD

**Issue by tanz-tilsontech** [mapzap/mapzap.github.io#3]
I'm wanting to use this, but would like to see if you can add some features that will make it a little more useful for me.

In the build.html:
- Add the ability to Add Tile Layer HTML. I have a tile layer that shows engineered routes and would like show them on the map.

- Add C3/D3 Charts (which would need alasql to work I suppose) (would be in the navbar)

- Add Refresh Button in the navbar

If these cannot be implemented, can you help me with the build out that I have?

I like the way you use:
- Filter the markers on map to filtered table
- Legend markers on the Table
- Legend popup on the navbar

**Comment by bmcbride** [comment]
These feature requests are out of the scope of this project, which is meant to be super simple with configuration via URL parameters.

**Comment by tanz-tilsontech** [comment]
I understand. Can you help me add a couple features on mine as its not URL based? I'll pay you if it's too much of an issue. Or is this something I can go through my Fulcrum Support to get help with?



Sent from my Verizon, Samsung Galaxy Tablet


-------- Original message --------
